In [1]:
import pandas as pd
import numpy as np
import re
import os
import csv

In [2]:
d = pd.read_csv('../data/snps_exps/UKBB_col21_1_assoc.csv', sep=',')

In [10]:
case = []
with open('../data/eid_filter/eid_filter.csv', 'r') as fp:
    reader = csv.reader(fp)
    head = next(fp)
    for line in reader:
        case.append(line[1])

eids = []
with open('../data/field_extraction/eids.csv', 'r') as fp:
    reader = csv.reader(fp)
    head = next(fp)
    for line in reader:
        eids.append(line[0])

In [13]:
import random
import math
random.shuffle(case)
random.shuffle(eids)

k = math.ceil(len(case) / 4 * 3)
validation_case = case[: k]
testing_case = case[k:]

In [14]:
validation_not_case = []
testing_not_case = []
for eid in eids:
    if not (eid in case):
        if len(validation_not_case) < len(validation_case):
            validation_not_case.append(eid)
        elif len(testing_not_case) < len(testing_not_case):
            testing_not_case.append(eid)
        else:
            break

In [20]:
print('validation case:', len(validation_case))
print('validation not case:', len(validation_not_case))
print('testing case:', len(testing_case))
print('testing not case:', len(testing_not_case))

validation case: 14851
validation not case: 7011
testing case: 4950
testing not case: 0


In [21]:
validation = validation_case + validation_not_case
testing = testing_case + testing_not_case

with open('validation.txt', w) as fp:
    for line in validation:
        fp.write(line)
        fp.write('\n')

with open('testing.txt', w) as fp:
    for line in testing:
        fp.write(line)
        fp.write('\n')

21862


In [5]:
with open('../data/snps_cad.txt', 'w') as outfp:
    with open('../data/UKBB_cad_valid.bim', 'r') as fp:
        for line in fp:
            line = re.split(r'\s+', line.strip())
            outfp.write(line[1])
            outfp.write('\n')

In [12]:
a = set()
with open('../data/features_selection/features_selection_data_dummy_info.csv', 'r') as fp:
    reader = csv.reader(fp)
    for line in reader:
        a.add(line[1].split('_')[0])

In [13]:
b = list(a)

In [14]:
len(b)

109

In [1]:
features_selection_data_infile = '../data/features_selection/features_selection_data.txt'
features_data = []
with open(features_selection_data_infile, 'r') as fp:
    for line in fp:
        data = line.strip().split()
        features_data.append(data)
        break

In [3]:
len(features_data[0])

502505

In [2]:
data = []
with open('../data/clean_data/raw_impute_data.txt', 'r') as fp:
    for line in fp:
        d = line.strip().split(' ')
        data.append(d)

In [4]:
d = np.asarray(data)

In [5]:
d.shape

(3, 19801)

In [6]:
d

array([['1.0', '1.0', '1.0', ..., '1.0', '1.0', '1.0'],
       ['34.0', '36.0', '38.0', ..., '10.0', '25.0', '18.0'],
       ['91.0', '95.0', '93.0', ..., '126.0', '100.0', '74.0']],
      dtype='<U17')

In [2]:
a = np.array([[1,2,4], [2.0, 3.9, 5.7]])

In [4]:
a.shape

(2, 3)

In [6]:
b = np.random.randint(-10, 10, (3,2))

In [7]:
np.dot(a, b)

array([[37. , 27. ],
       [66.2, 40.3]])

In [17]:
a = "13 161 461 781 6846 384 34 384 38 354"
b = np.asarray(a.split(" "))

In [18]:
pd.DataFrame(data=b, columns=['data'])

data
0    13
1   161
2   461
3   781
4  6846
5   384
6    34
7   384
8    38
9   354

In [24]:
pd.DataFrame(data=[1,2,5,7,5,8,2,8,3])

0
0  1
1  2
2  5
3  7
4  5
5  8
6  2
7  8
8  3

In [14]:
import os
for root, dirs, files in os.walk('../data/'):
    print(root)
    print(dirs)
    print(files)
    break

../data/
['clean_data', 'eid_filter', 'features_selection', 'field_extraction']
['cols_filter.txt', 'cols_type.txt']


In [5]:
import numpy as np
a = np.genfromtxt('../data/field_extraction/fields/field_19.txt')

In [7]:
a.dtype

dtype('float64')

In [9]:
b = np.load('../data/field_extraction/eids.npy')

In [10]:
b

array([1000011, 1000026, 1000032, ..., 1029989, 1029993, 1030004],
      dtype=int64)

In [13]:
np.where(b == 1000011)[0]

array([0], dtype=int64)

In [19]:
c = np.genfromtxt('../data/eid_filter/eid_filter.csv', delimiter=',', dtype=np.int32)

array([     5,     24,     58, ..., 491190, 496333, 498690])

In [22]:
y = np.zeros(502506)

In [23]:
y[c[1:, 0]] = 1

In [24]:
y

array([0., 0., 0., ..., 0., 0., 0.])

In [30]:
y[491191]

0.0

In [34]:
d = np.genfromtxt('../data/clean_data/raw_impute_data.txt')

In [32]:
d

array([[  1.,   1.,   1., ...,   1.,   1.,   1.],
       [ 34.,  36.,  38., ...,  10.,  25.,  18.],
       [ 91.,  95.,  93., ..., 126., 100.,  74.]])

In [35]:
d.shape

(2, 502506)

In [48]:
 x = []
with open ('../data/clean_data/raw_impute_data.txt') as fp:
    for line in fp:
        if line == '\n':
            continue
        d = line.strip().split()
        x.append(d)

In [49]:
x = np.asarray(x, dtype=np.float64)

In [56]:
x[0].tolist()

[46.0,
 48.0,
 16.0,
 26.0,
 18.0,
 34.0,
 16.0,
 12.0,
 20.0,
 20.0,
 20.0,
 24.0,
 44.0,
 20.0,
 22.0,
 28.0,
 23.0,
 30.0,
 24.0,
 28.0,
 28.0,
 34.0,
 30.0,
 20.0,
 36.0,
 28.0,
 26.0,
 34.0,
 18.0,
 34.0,
 18.0,
 28.0,
 26.0,
 39.0,
 16.0,
 12.0,
 34.0,
 20.0,
 28.0,
 45.0,
 32.0,
 45.0,
 39.0,
 17.0,
 53.0,
 38.0,
 36.0,
 22.0,
 20.0,
 28.0,
 34.0,
 35.0,
 22.0,
 44.0,
 30.0,
 24.0,
 20.0,
 50.0,
 38.0,
 0.0,
 28.0,
 22.0,
 18.0,
 37.0,
 18.0,
 28.0,
 35.0,
 22.0,
 20.0,
 18.0,
 30.0,
 24.0,
 15.0,
 36.0,
 22.0,
 19.0,
 21.0,
 34.0,
 14.0,
 31.0,
 40.0,
 30.0,
 46.0,
 42.0,
 26.0,
 32.0,
 12.0,
 36.0,
 34.0,
 46.0,
 37.0,
 26.0,
 36.0,
 20.0,
 22.0,
 27.0,
 35.0,
 32.0,
 47.0,
 26.0,
 30.0,
 25.0,
 28.0,
 54.0,
 32.0,
 19.0,
 10.0,
 30.0,
 20.0,
 20.0,
 50.0,
 25.0,
 56.0,
 28.0,
 35.0,
 42.0,
 22.0,
 28.0,
 22.0,
 32.0,
 18.0,
 36.0,
 26.0,
 30.0,
 20.0,
 24.0,
 15.0,
 34.0,
 26.0,
 46.0,
 26.0,
 21.0,
 38.0,
 32.0,
 32.0,
 36.0,
 25.0,
 28.0,
 10.0,
 54.0,
 20.0,
 22.0,
 28.0,


In [53]:
train = x[0]

In [55]:
train.reshape((-1, 1))

array([[46.],
       [48.],
       [16.],
       ...,
       [14.],
       [38.],
       [26.]])

In [54]:
train.shape

(502506,)

In [39]:
k = train.squeeze()

In [41]:
k.tolist()

[46.0,
 48.0,
 16.0,
 26.0,
 18.0,
 34.0,
 16.0,
 12.0,
 20.0,
 20.0,
 20.0,
 24.0,
 44.0,
 20.0,
 22.0,
 28.0,
 23.0,
 30.0,
 24.0,
 28.0,
 28.0,
 34.0,
 30.0,
 20.0,
 36.0,
 28.0,
 26.0,
 34.0,
 18.0,
 34.0,
 18.0,
 28.0,
 26.0,
 39.0,
 16.0,
 12.0,
 34.0,
 20.0,
 28.0,
 45.0,
 32.0,
 45.0,
 39.0,
 17.0,
 53.0,
 38.0,
 36.0,
 22.0,
 20.0,
 28.0,
 34.0,
 35.0,
 22.0,
 44.0,
 30.0,
 24.0,
 20.0,
 50.0,
 38.0,
 0.0,
 28.0,
 22.0,
 18.0,
 37.0,
 18.0,
 28.0,
 35.0,
 22.0,
 20.0,
 18.0,
 30.0,
 24.0,
 15.0,
 36.0,
 22.0,
 19.0,
 21.0,
 34.0,
 14.0,
 31.0,
 40.0,
 30.0,
 46.0,
 42.0,
 26.0,
 32.0,
 12.0,
 36.0,
 34.0,
 46.0,
 37.0,
 26.0,
 36.0,
 20.0,
 22.0,
 27.0,
 35.0,
 32.0,
 47.0,
 26.0,
 30.0,
 25.0,
 28.0,
 54.0,
 32.0,
 19.0,
 10.0,
 30.0,
 20.0,
 20.0,
 50.0,
 25.0,
 56.0,
 28.0,
 35.0,
 42.0,
 22.0,
 28.0,
 22.0,
 32.0,
 18.0,
 36.0,
 26.0,
 30.0,
 20.0,
 24.0,
 15.0,
 34.0,
 26.0,
 46.0,
 26.0,
 21.0,
 38.0,
 32.0,
 32.0,
 36.0,
 25.0,
 28.0,
 10.0,
 54.0,
 20.0,
 22.0,
 28.0,


In [57]:
pd.read_csv('../data/field_extraction/eids.csv').to_numpy().reshape([-1])

array([1000011, 1000026, 1000032, ..., 1072855, 1072863, 1072872],
      dtype=int64)

In [5]:
cols_id = []
with open('../data/cols_type.txt', 'r') as fp:
    for line in fp:
        row = line.strip().split('\t')
        cols_id.append(row[1])

In [6]:
cols_id.remove('20001')

In [7]:
cols_id.remove('20002')

In [10]:
source_file = '../ukb41910.csv'
df = pd.read_csv(source_file, encoding='cp936', nrows=1)
columns = df.columns

In [18]:
columns

Index(['eid', '3-0.0', '3-1.0', '3-2.0', '3-3.0', '4-0.0', '4-1.0', '4-2.0',
       '4-3.0', '5-0.0',
       ...
       '105010-2.0', '105010-3.0', '105010-4.0', '105030-0.0', '105030-1.0',
       '105030-2.0', '105030-3.0', '105030-4.0', '110005-0.0', '110006-0.0'],
      dtype='object', length=18114)

In [28]:
fields = []
all_cols_idx=[]
for field_id in cols_id[:200]:
    cols_idx = []
    for idx, col in enumerate(columns):
        if re.search('^' + field_id + '-', col):
            cols_idx.append(idx)
    if len(cols_idx) == 0:
        continue
    all_cols_idx.append(cols_idx)
    fields.append(field_id)

In [29]:
len(fields)

200

In [34]:
with open(source_file, 'r') as fp:
    reader = csv.reader(fp)
    for i, cols in enumerate(reader):
        if i == 0:
             continue
        cols = np.asarray(cols)
        for k, cols_idx in enumerate(all_cols_idx):
            print('filed:', fields[k])
            A = cols[cols_idx]
            B = 'NAN'
            for C in A:
                if C != '':
                    B = C
            print(A)
        break

filed: 3
['439' '' '' '']
filed: 4
['453' '' '' '']
filed: 5
['201' '' '' '']
filed: 6
['38' '' '' '']
filed: 19
['2']
filed: 21
['1' '' '' '']
filed: 31
['1']
filed: 34
['1948']
filed: 36
['001050' '' '' '']
filed: 37
['' '' '' '']
filed: 38
['001354' '' '' '']
filed: 39
['002028' '' '' '']
filed: 40
['001192' '' '' '']
filed: 41
['001157' '' '' '']
filed: 42
['03123' '' '' '']
filed: 43
['001490' '' '' '']
filed: 44
['002956' '' '' '']
filed: 45
['002113' '' '' '']
filed: 46
['46' '' '' '']
filed: 47
['46' '' '' '']
filed: 48
['93' '' '' '']
filed: 49
['101' '' '' '']
filed: 50
['172' '' '' '']
filed: 51
['136' '' '' '']
filed: 52
['5']
filed: 53
['2007-12-21' '' '' '']
filed: 54
['11001' '' '' '']
filed: 55
['12' '' '' '']
filed: 77
['0.9']
filed: 78
['']
filed: 84
['' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '']
filed: 87
['50' '57' '2002' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' ''
 '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '

In [19]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [20]:
class MyModel(keras.Model):
    def __init__(self, fixed_field_index):
        super(MyModel, self).__init__()
        self.fixed_field_index = fixed_field_index
        self.fc1 = keras.layers.Dense(1)
        self.fc2 = keras.layers.Dense(1)
        pass

    def call(self, inputs, training=None):
        if len(self.fixed_field_index) > 0:
            control_input = tf.gather(inputs, self.fixed_field_index, axis=1)
        c = np.zeros(inputs.shape[1])
        c[self.fixed_field_index] = 1
        c = np.argwhere(c == 0).squeeze()
        train_input = tf.gather(inputs, c, axis=1)
        if len(self.fixed_field_index) < 1:
            out = self.fc1(train_input)
        else:
            out1 = self.fc1(train_input)
            out2 = self.fc2(control_input)
            out = out1 + out2
        return out

In [21]:
m = MyModel([])
m.build(input_shape=[None, 10])

Instructions for updating:
The `validate_indices` argument has no effect. Indices are always validated on CPU and never validated on GPU.


In [22]:
m.load_weights('../data/model_wights/MyModel_1.ckpt')

In [24]:
weights = np.array(m.fc1.trainable_variables[0])

In [35]:
weights.dtype

dtype('float32')

In [39]:
x = np.array([1,2.0,3.5,1e-9,5,0,7,8,9])

In [40]:
x.dtype

dtype('float64')

In [41]:
x[~(x == 0)]

array([1.0e+00, 2.0e+00, 3.5e+00, 1.0e-09, 5.0e+00, 7.0e+00, 8.0e+00,
       9.0e+00])

In [46]:
np.argsort(x)[-1::-1]

array([8, 7, 6, 4, 2, 1, 0, 3, 5], dtype=int64)

In [97]:
epoch = 5
lr = 0.01
batchsz = 512

train_x = np.random.normal(size=(200, 30))
pca_hidden_layers = [10, 5]
encoder_hidden = []
for neuro_num in pca_hidden_layers:
    encoder_hidden.append(tf.keras.layers.Dense(neuro_num, activation=tf.nn.sigmoid))
encoder = keras.Sequential(encoder_hidden)  

decoder_hidden = []
if len(pca_hidden_layers) > 1:
    for neuro_num in pca_hidden_layers[-2::-1]:
        decoder_hidden.append(tf.keras.layers.Dense(neuro_num, activation=tf.nn.sigmoid))
decoder_hidden.append(tf.keras.layers.Dense(train_x.shape[1], activation=tf.nn.sigmoid))
decoder = keras.Sequential(decoder_hidden)

In [98]:
encoder.build(input_shape=[None, train_x.shape[1]])

In [99]:
decoder.build(input_shape=[None, 5])

In [115]:
train_db = tf.data.Dataset.from_tensor_slices(train_x).shuffle(train_x.shape[0]).batch(batchsz)
optimizer = tf.optimizers.Adam(learning_rate=lr)
for epo in range(epoch):
    for step, x in enumerate(train_db):
        with tf.GradientTape() as tape:
            output = encoder(x)
            output = decoder(output)
            loss = tf.keras.losses.mean_squared_error(x, output)
        grades = tape.gradient(loss, [encoder.trainable_variables, decoder.trainable_variables])
        optimizer.apply_gradients(zip(grades[0], encoder.trainable_variables))
        optimizer.apply_gradients(zip(grades[1], decoder.trainable_variables))
        print("epoch:", epo, "step:", step)

epoch: 0 step: 0
epoch: 1 step: 0
epoch: 2 step: 0
epoch: 3 step: 0
epoch: 4 step: 0


In [1]:
from sklearn.datasets import load_boston
import numpy as np

In [2]:
boston = load_boston()

In [3]:
boston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [4]:
boston['data'].shape

(506, 13)

In [5]:
boston['data'][:, [3, 8]]

array([[0., 1.],
       [0., 2.],
       [0., 2.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [6]:
class HEOM():
    def __init__(self, X, cat_ix, nan_equivalents=[np.nan, 0], normalised="normal"):
        """ Heterogeneous Euclidean-Overlap Metric
        Distance metric class which initializes the parameters
        used in heom function
        
        Parameters
        ----------
        X : array-like of shape = [n_rows, n_features]
            Dataset that will be used with HEOM. Needs to be provided
            here because minimum and maximimum values from numerical
            columns have to be extracted
        
        cat_ix : array-like of shape = [cat_columns_number]
            List containing categorical feature indices
        
        cat_ix : array-like of shape = [x]
            List containing missing values indicators
        normalised: string
            normalises euclidan distance function for numerical variables
            Can be set as "std". Default is a column range
        Returns
        -------
        None
        """      
               
        self.nan_eqvs = nan_equivalents
        self.cat_ix = cat_ix
        self.col_ix = [i for i in range(X.shape[1])]
        # Get the normalization scheme for numerical variables
        if normalised == "std":
            self.range = 4* np.nanstd(X, axis = 0)
        else:
            self.range = np.nanmax(X, axis = 0) - np.nanmin(X, axis = 0)
    
    def heom(self, x, y):
        """ Distance metric function which calculates the distance
        between two instances. Handles heterogeneous data and missing values.
        It can be used as a custom defined function for distance metrics
        in Scikit-Learn
        
        Parameters
        ----------
        x : array-like of shape = [n_features]
            First instance 
            
        y : array-like of shape = [n_features]
            Second instance
        Returns
        -------
        result: float
            Returns the result of the distance metrics function
        """
        # Initialise results' array
        results_array = np.zeros(x.shape)

        # Get indices for missing values, if any
        nan_x_ix = np.flatnonzero( np.logical_or(np.isin(x, self.nan_eqvs), np.isnan(x)))
        nan_y_ix = np.flatnonzero( np.logical_or(np.isin(y, self.nan_eqvs), np.isnan(y)))
        nan_ix = np.unique(np.concatenate((nan_x_ix, nan_y_ix)))
        # Calculate the distance for missing values elements
        results_array[nan_ix] = 1

        # Get categorical indices without missing values elements
        cat_ix = np.setdiff1d(self.cat_ix, nan_ix)
        # Calculate the distance for categorical elements
        results_array[cat_ix]= np.not_equal(x[cat_ix], y[cat_ix]) * 1 # use "* 1" to convert it into int

        # Get numerical indices without missing values elements
        num_ix = np.setdiff1d(self.col_ix, self.cat_ix)
        num_ix = np.setdiff1d(num_ix, nan_ix)
        # Calculate the distance for numerical elements
        results_array[num_ix] = np.abs(x[num_ix] - y[num_ix]) / self.range[num_ix]
        
        # Return the final result
        # Square root is not computed in practice
        # As it doesn't change similarity between instances
        return np.sum(np.square(results_array))

In [7]:
# Load the dataset from sklearn
boston = load_boston()
boston_data = boston["data"]
# Categorical variables in the data
categorical_ix = [3, 8]
# The problem here is that NearestNeighbors can't handle np.nan
# So we have to set up the NaN equivalent
nan_eqv = 12345

# Introduce some missingness to the data for the purpose of the example
row_cnt, col_cnt = boston_data.shape
for i in range(row_cnt):
    for j in range(col_cnt):
        rand_val = np.random.randint(20, size=1)
        if rand_val == 10:
            boston_data[i, j] = nan_eqv

# Declare the HEOM with a correct NaN equivalent value
heom_metric = HEOM(boston_data, categorical_ix, nan_equivalents = [nan_eqv])

In [15]:
heom_metric.heom(boston_data[0], boston_data[1])

2.0000221617012914

In [16]:
from sklearn.neighbors import DistanceMetric

In [17]:
dist = DistanceMetric.get_metric('hamming')

In [18]:
x = ['abc', 'lzm', 'hello']

In [19]:
dist.pairwise(x)

ValueError: could not convert string to float: 'abc'

In [20]:
from collections import defaultdict

In [25]:
a = {}

In [30]:
'a' in a.keys()

False

In [31]:
x = np.array([11111, 11111, 'asdasd', 'asdasd'])

In [32]:
x

array(['11111', '11111', 'asdasd', 'asdasd'], dtype='<U11')

In [34]:
y = np.array([1, 1, 3, 3])

In [35]:
y == 1

array([ True,  True, False, False])

In [36]:
x == '11111'

array([ True,  True, False, False])

In [37]:
x

array(['11111', '11111', 'asdasd', 'asdasd'], dtype='<U11')

In [38]:
x.flatten()

array(['11111', '11111', 'asdasd', 'asdasd'], dtype='<U11')

In [39]:
x = np.array([[1], [2], [3]])

In [46]:
np.argwhere(x[:, 0] == 1)

array([[0]], dtype=int64)

In [44]:
np.argwhere(x[:, 0] == 1).flatten()

array([0], dtype=int64)

In [48]:
np.argwhere([[1,2,3], [4,5,6]])

array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [1, 2]], dtype=int64)

In [164]:
import numpy as np


class VDM():
    def __init__(self, X, Y, cat_ix):
        """ Value Difference Metric
        Distance metric class which initializes the parameters
        used in vdm() function

        Parameters
        ----------
        X : array-like of shape = [n_rows, n_features]
            First instance

        y_ix : int array-like, list of shape [1]
            Single element array with indices for categorical output variable
            If y is numerical it should be converted to categorical (if it makes sense)

        cat_ix : array-like of shape = [cat_columns_number]
            List containing categorical feature indices

        Returns
        -------
        None
        """
        self.cat_ix = cat_ix
        self.col_ix = [i for i in range(X.shape[1])]
        self.Y = Y
        self.classes = np.unique(Y)

        array_len = 0
        # Get the max no. of unique classes within columns to initialize the array
        for ix in self.cat_ix:
            max_val = len(np.unique(X[:, ix]))
            if max_val > array_len:
                array_len = max_val

        # Store the list of unique classes elements for each categorical column
        # self.col_ix is used here for clearer indices assignment
        self.unique_attributes = np.full((array_len, len(self.col_ix)), fill_value=-1)
        for ix in self.cat_ix:
            unique_vals = np.unique(X[:, ix])
            self.unique_attributes[0:len(unique_vals), ix] = unique_vals

        # Declare the 3D numpy array which holds specifc count for each attribute
        # for each column for each output class
        # +1 in len(self.classes) + 1 is to store the sum (N_a,x) in the last element
        self.final_count = np.zeros((len(self.col_ix), self.unique_attributes.shape[0], len(self.classes) + 1))
        # For each column
        for i, col in enumerate(self.cat_ix):
            # For each attribute value in the column
            for j, attr in enumerate(self.unique_attributes[:, col]):
                # If attribute exists
                if attr != -1:
                    # For each output class value
                    for k, val in enumerate(self.classes):
                        # Get an attribute count for each output class
                        row_ixs = np.argwhere(X[:, col] == attr)
                        cnt = np.sum(Y[row_ixs] == val)
                        self.final_count[col, j, k] = cnt
                    # Get a sum of all occurences
                    self.final_count[col, j, -1] = np.sum(self.final_count[col, j, :])

    def vdm(self, x, y, nan_ix=[]):
        """ Value Difference Metric
        Distance metric function which calculates the distance
        between two instances. Handles heterogeneous data and missing values.
        For categorical variables, it uses conditional probability
        that the output class is given 'c' when attribute 'a' has a value of 'n'.
        It can be used as a custom defined function for distance metrics
        in Scikit-Learn
        Parameters
        ----------
        x : array-like of shape = [n_features]
            First instance

        y : array-like of shape = [n_features]
            Second instance
        Returns
        -------
        result: float
            Returns the result of the distance metrics function
        """
        result = np.zeros(len(x))
        cat_ix = np.setdiff1d(self.cat_ix, nan_ix)

        for i in cat_ix:
            # Get indices to access the final_count array
            x_ix = np.argwhere(self.unique_attributes[:, i] == x[i]).flatten()
            y_ix = np.argwhere(self.unique_attributes[:, i] == y[i]).flatten()
            # Get the count to calculate the conditional probability
            N_ax = self.final_count[i, x_ix, -1].flatten()
            N_ay = self.final_count[i, y_ix, -1].flatten()
            N_axc = self.final_count[i, x_ix].flatten()
            N_ayc = self.final_count[i, y_ix].flatten()
            temp_result = 0
            if N_ax != 0 and N_ay != 0:
                temp_result = abs(N_axc / N_ax - N_ayc / N_ay)
                temp_result = np.sum(temp_result)
            else:
                # print("Division by zero is not allowed!")
                pass
            result[i] = temp_result
        return result


In [165]:
class HVDM(VDM):
    def __init__(self, X, Y, cat_ix, nan_equivalents=[np.nan, 0], normalised="variance"):
        """ Heterogeneous Value Difference Metric
        Distance metric class which initializes the parameters
        used in hvdm() function

        Parameters
        ----------
        X : array-like of shape = [n_rows, n_features]
            Dataset that will be used with HVDM. Needs to be provided
            here because minimum and maximimum values from numerical
            columns have to be extracted

        y_ix : int array-like, list of shape [1]
            Single element array with indices for the categorical output variable
            If y is numerical it should be converted to categorical (if it makes sense)

        cat_ix : array-like of shape = [cat_columns_number]
            List containing categorical feature indices

        cat_ix : array-like of shape = [x]
            List containing missing values indicators
        normalised: string
            Normalises euclidan distance function for numerical variables
            Can be set as "std". The other option is a column range
        Returns
        -------
        None
        """
        # Initialize VDM object
        super().__init__(X, Y, cat_ix)
        self.nan_eqvs = nan_equivalents
        self.cat_ix = cat_ix
        self.col_ix = [i for i in range(X.shape[1])]
        # Get the normalization scheme for numerical variables
        if normalised == "std":
            self.range = 4 * np.nanstd(X, axis=0)
        else:
            self.range = np.nanmax(X, axis=0) - np.nanmin(X, axis=0)

    def hvdm(self, x, y):
        """ Heterogeneous Value Difference Metric
        Distance metric function which calculates the distance
        between two instances. Handles heterogeneous data and missing values.
        For categorical variables, it uses conditional probability
        that the output class is given 'c' when attribute 'a' has a value of 'n'.
        For numerical variables, it uses a normalized Euclidan distance.
        It can be used as a custom defined function for distance metrics
        in Scikit-Learn

        Parameters
        ----------
        x : array-like of shape = [n_features]
            First instance

        y : array-like of shape = [n_features]
            Second instance
        Returns
        -------
        result: float
            Returns the result of the distance metrics function
        """
        # Initialise results array
        results_array = np.zeros(x.shape)

        # Get indices for missing values, if any
        nan_x_ix = np.flatnonzero(np.logical_or(np.isin(x, self.nan_eqvs), np.isnan(x)))
        nan_y_ix = np.flatnonzero(np.logical_or(np.isin(y, self.nan_eqvs), np.isnan(y)))
        nan_ix = np.unique(np.concatenate((nan_x_ix, nan_y_ix)))
        # Calculate the distance for missing values elements
        results_array[nan_ix] = 1

        # Get categorical indices without missing values elements
        if len(self.cat_ix) != 0:
            cat_ix = np.setdiff1d(self.cat_ix, nan_ix)
        else:
            cat_ix = self.cat_ix
        # Calculate the distance for categorical elements
        results_array[cat_ix] = super().vdm(x, y, nan_ix)[cat_ix]
        # Get numerical indices without missing values elements
        num_ix = np.setdiff1d(self.col_ix, self.cat_ix)
        num_ix = np.setdiff1d(num_ix, nan_ix)
        # Calculate the distance for numerical elements
        results_array[num_ix] = np.abs(x[num_ix] - y[num_ix]) / self.range[num_ix]

        # Return the final result
        # Square root is not computed in practice
        # As it doesn't change similarity between instances
        return np.sum(np.square(results_array))

In [166]:
# Example code of how the HEOM metric can be used together with Scikit-Learn
import numpy as np
from sklearn.neighbors import NearestNeighbors
from sklearn.datasets import load_boston, load_iris
# Importing a custom metric class

# Load the dataset from sklearn
db = load_iris()
data = db["data"]
# Categorical variables in the data
categorical_ix = [3, 8]
# The problem here is that NearestNeighbors can't handle np.nan
# So we have to set up the NaN equivalent
nan_eqv = 12345

# Introduce some missingness to the data for the purpose of the example
# row_cnt, col_cnt = data.shape
# for i in range(row_cnt):
#     for j in range(col_cnt):
#         rand_val = np.random.randint(20, size=1)
#         if rand_val == 10:
#             data[i, j] = nan_eqv
target = db['target']
hvdm_metrix = HVDM(data, target, cat_ix=categorical_ix)

In [167]:
neighbor = NearestNeighbors(metric = hvdm_metrix.hvdm)
neighbor.fit(boston_data)

E:\conda\envs\TFGPU\lib\site-packages\ipykernel_launcher.py:97: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.


NearestNeighbors(metric=<bound method HVDM.hvdm of <__main__.HVDM object at 0x0000027C20010388>>)

In [168]:
result = neighbor.kneighbors(boston_data[0].reshape(1, -1), n_neighbors = 5)
print(result)

(array([[1.        , 1.93754132, 1.94552624, 2.00006195, 2.91960629]]), array([[  0, 347, 286, 498,  57]], dtype=int64))


E:\conda\envs\TFGPU\lib\site-packages\ipykernel_launcher.py:97: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.


In [161]:
hvdm_metrix.hvdm(boston_data[0], boston_data[100])

1.8329861937301648e-07

In [111]:
hvdm_metrix.hvdm(boston_data[0], boston_data[200])

3.9863598779320033