In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PRS_models import *

In [2]:
# phenotype data loading
d_file = '../../data/features_selection/features_selection_data_dummy_data.txt'
d_info_file = '../../data/features_selection/features_selection_data_dummy_info.csv'
data = np.genfromtxt(d_file)
data_info = pd.read_csv(d_info_file, header=None, names=['Type', 'id', 'Description'])

KeyboardInterrupt: 

In [13]:
data_info

Type       id                                 Description
0    Categorical  20117_0                      Alcohol drinker status
1    Categorical  20117_1                      Alcohol drinker status
2    Categorical  20117_2                      Alcohol drinker status
3    Categorical   1558_1                   Alcohol intake frequency.
4    Categorical   1558_2                   Alcohol intake frequency.
..           ...      ...                                         ...
256  Categorical   3059_0                              Result ranking
257  Categorical   3059_1                              Result ranking
258  Categorical   3059_2                              Result ranking
259  Categorical   3090_0  Used an inhaler for chest within last hour
260  Categorical   3090_1  Used an inhaler for chest within last hour

[261 rows x 3 columns]

In [19]:
numerical_phenotype_idx = []
classification_phenotype_idx = []
idx = 0
while idx < data_info.shape[0]:
    k = idx
    id = str.split(data_info.iloc[idx]['id'], sep='_')[0]
    if not data_info.iloc[idx]['Type'] == 'Categorical':
        numerical_phenotype_idx.append(idx)
        idx += 1
    else:
        while k < data_info.shape[0]:
            if str.startswith(data_info.iloc[k]['id'], id):
                k += 1
            else:
                break
        classification_phenotype_idx.append((idx, k))
        idx = k

In [27]:
a = np.random.randint(0, 5, size=(50, 10))
b = np.random.randint(0, 5, size=(50, 1))
c = np.random.randint(0, 5, size=(50, 1))

In [32]:
from sklearn.model_selection import train_test_split
len(train_test_split(a,b,c, test_size=0.25, random_state=999, shuffle=True))

6

In [72]:
d = tf.constant(data.T)

In [73]:
d.shape

TensorShape([502505, 261])

In [107]:
d[:, numerical_phenotype_idx[0]].shape

TensorShape([502505])

In [109]:
a = tf.random.normal(shape=[2,1], dtype=tf.float64)

In [127]:
tf.reshape(d[:, numerical_phenotype_idx[0]], shape=[1, -1])

<tf.Tensor: shape=(1, 502505), dtype=float64, numpy=array([[10.,  8., 20., ...,  8., 30.,  0.]])>

In [111]:
tf.matmul(a, tf.reshape(d[:, numerical_phenotype_idx[0]], shape=[1, -1]))

<tf.Tensor: shape=(2, 502505), dtype=float64, numpy=
array([[-20.24654047, -16.19723237, -40.49308093, ..., -16.19723237,
        -60.7396214 ,   0.        ],
       [  0.12628107,   0.10102486,   0.25256214, ...,   0.10102486,
          0.37884321,   0.        ]])>

In [100]:
numerical_x = [d[:, idx] for idx in numerical_phenotype_idx]

In [101]:
len(numerical_phenotype_idx)

61

In [102]:
len(numerical_x)

61

In [103]:
categorical_x = [d[:, idx_s:idx_e] for (idx_s, idx_e) in classification_phenotype_idx]

In [105]:
categorical_x[0].shape

TensorShape([502505, 3])

In [115]:
d.ndim

2

In [122]:
tf.transpose(d[:, numerical_phenotype_idx[0]])

<tf.Tensor: shape=(502505,), dtype=float64, numpy=array([10.,  8., 20., ...,  8., 30.,  0.])>

In [128]:
tf.reshape(d[:, numerical_phenotype_idx[0]], shape=(-1, 1)).shape

TensorShape([502505, 1])

In [131]:
tf.squeeze(categorical_x[0])

<tf.Tensor: shape=(502505, 3), dtype=float64, numpy=
array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])>

In [1]:
from PRS_models import *

In [2]:
mm = myModel(11, n_categorical_phenotype_feature=[2, 3, 4])

In [3]:
prs = PRS_model()

In [4]:
mm.trainable_variables

[<tf.Variable 'Variable:0' shape=(2, 1) dtype=float64, numpy=
 array([[0.53796072],
        [0.95599885]])>,
 <tf.Variable 'Variable:0' shape=(2, 1) dtype=float64, numpy=
 array([[ 0.26807177],
        [-0.52506593]])>,
 <tf.Variable 'Variable:0' shape=(2, 1) dtype=float64, numpy=
 array([[-0.64183402],
        [-0.70885978]])>,
 <tf.Variable 'Variable:0' shape=(2, 1) dtype=float64, numpy=
 array([[-0.23523784],
        [ 0.12690197]])>,
 <tf.Variable 'Variable:0' shape=(2, 1) dtype=float64, numpy=
 array([[ 0.84075384],
        [-1.73005573]])>,
 <tf.Variable 'Variable:0' shape=(2, 1) dtype=float64, numpy=
 array([[0.679603  ],
        [0.17243057]])>,
 <tf.Variable 'Variable:0' shape=(2, 1) dtype=float64, numpy=
 array([[2.02928376],
        [0.32181326]])>,
 <tf.Variable 'Variable:0' shape=(2, 1) dtype=float64, numpy=
 array([[0.87962562],
        [1.74268748]])>,
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=float64, numpy=
 array([[-0.74027127,  0.74682451],
        [-0.19698095, 